### ISSUE TITLE
V1 of Tauri

### ISSUE THREAD

**Issue by TartanLeGrand** [capacitor-community/tauri#3]
### Migrate to Tauri version 1.0. 

This allows to go to a stable version of Tauri and also to add the features related with the issue  [https://github.com/capacitor-community/tauri/issues/2](https://github.com/capacitor-community/tauri/issues/2).

Version 1 was released on 2022/06/19 => [Tauri v1.0](https://tauri.app/fr/blog/2022/06/19/tauri-1-0)

**Comment by han9088** [comment]
> ### Migrate to Tauri version 1.0.
> This allows to go to a stable version of Tauri and also to add the features related with the issue #2.
> 
> Version 1 was released on 2022/06/19 => [Tauri v1.0](https://tauri.app/fr/blog/2022/06/19/tauri-1-0)

This repo seems no longer maintained. I refactor it to [nawbc/capacitor-tauri](https://github.com/nawbc/capacitor-tauri)

**Comment by TartanLeGrand** [comment]
> > ### Migrate to Tauri version 1.0.
> > This allows to go to a stable version of Tauri and also to add the features related with the issue #2.
> > Version 1 was released on 2022/06/19 => [Tauri v1.0](https://tauri.app/fr/blog/2022/06/19/tauri-1-0)
> 
> This repo seems no longer maintained. I refactor it to [nawbc/capacitor-tauri](https://github.com/nawbc/capacitor-tauri)

Stop use Capacitor, because Tauri 2 integrate Mobile too. :wave:
