### ISSUE TITLE
Hi, is this project still active?

### ISSUE THREAD

**Issue by benajaero** [capacitor-community/tauri#4]

**Comment by ThatOneCalculator** [comment]
:(

**Comment by Erudition** [comment]
Same question here

**Comment by coopbri** [comment]
I would be open to taking & maintaining this project. @IT-MikeS let me know how best to go about this if you're interested! Lots of great work you have here that I would love to uphold.

**Comment by IT-MikeS** [comment]
@coopbri sure thing, I’ll add you as a collaborator for now that way you can play with the repo more freely.

**Comment by coopbri** [comment]
@IT-MikeS tried to [ping you on Twitter](https://twitter.com/0xcoop/status/1685807368901443585), would you mind following me there so I can DM you about this project or send e.g. an email address?
